Goal of this script is to obtain 
vertex, edge, face 


V, EV

In [2]:
pwd()


"/home/mjirik/projects/lario3d.jl/notebooks"

# Read obj file

In [3]:

f = open("../test/smallbb2.obj");
lines = readlines(f)

nvertices = 0
nfaces = 0
for line in lines
    if line[1] == 'v'
        nvertices = nvertices + 1
    elseif line[1] == 'f'
        nfaces = nfaces + 1
    end
end
    


In [4]:
A = rand(4,3);

B = view(A, 1:3, 1:2);

for i in eachindex(B)
   @show i
end


i = CartesianIndex{2}((1,1))
i = CartesianIndex{2}((2,1))
i = CartesianIndex{2}((3,1))
i = CartesianIndex{2}((1,2))
i = CartesianIndex{2}((2,2))
i = CartesianIndex{2}((3,2))


In [5]:
B[1,2]

0.48162123680398006

In [6]:

vertices = Array(Float64, nvertices + 1, 3)
faces = Array(Int64, nfaces + 1 , 3)
print(size(vertices))
ivertices = 1
ifaces = 1

for line in lines
    lsplit = split(line)
    if line[1] == 'v'
        for i=2:4
            vertices[ivertices, i - 1] = parse(Float64, lsplit[i])
        end
        ivertices = nvertices + 1
    elseif line[1] == 'f'
        for i=2:4
            faces[ifaces, i - 1] = parse(Int64, lsplit[i])
        end
        ifaces = ifaces + 1
    end
end


(1193,3)

# Check Julia

In [7]:
dcta = Dict("a" => 1, "b" => 2, "c" => 3)
dcta["f"] = 13
dcta

Dict{String,Int64} with 4 entries:
  "f" => 13
  "c" => 3
  "b" => 2
  "a" => 1

In [8]:
(1 , 5)


A = [(1,5), (15,18), (17,16,"asd"), (18,1,1)]

4-element Array{Tuple{Int64,Int64,Vararg{Any,N}},1}:
 (1,5)        
 (15,18)      
 (17,16,"asd")
 (18,1,1)     

In [9]:
i = 3
sort([faces[i, 1],  faces[i, 2]])

2-element Array{Int64,1}:
  9
 10

## Vertices

In [49]:
V = vertices

1193×3 Array{Float64,2}:
 1.0           2.0           1.0         
 3.47378e-316  1.31916e-321  0.0         
 2.122e-314    3.46485e-316  2.17292e-311
 3.47378e-316  6.95251e-310  6.36599e-314
 2.122e-314    1.28457e-321  1.061e-313  
 2.27616e-320  1.33892e-321  1.4854e-313 
 7.42699e-313  3.37857e-316  3.45846e-323
 0.0           6.95251e-310  2.122e-314  
 0.0           4.69362e-322  4.94066e-324
 3.47377e-316  1.35868e-321  0.0         
 3.47377e-316  3.46922e-316  2.17292e-311
 3.47378e-316  6.95251e-310  6.93956e-310
 0.0           8.06315e-321  8.48798e-314
 ⋮                                       
 3.98711e-321  2.122e-314    3.37857e-316
 1.2401e-321   3.47471e-316  6.95251e-310
 2.11874e-316  3.47472e-316  1.45255e-321
 6.95251e-310  4.94066e-324  7.1936e-321 
 0.0           3.47503e-316  3.37857e-316
 1.26975e-321  2.122e-314    6.95251e-310
 3.37857e-316  3.47507e-316  1.36856e-321
 6.95251e-310  3.47471e-316  7.12937e-321
 0.0           3.47471e-316  3.46922e-316
 1.29939e

## Edges

In [37]:
# Eset = Set()
Epl = []
EVpl = []
FEpl = Array(Int64, nfaces + 1 , 3)

for i = 1:nfaces
    
    push!(EVpl, sort([faces[i, 1], faces[i, 2]]))
    push!(EVpl, sort([faces[i, 2], faces[i, 3]]))
    push!(EVpl, sort([faces[i, 3], faces[i, 1]]))
    
    FEpl[i, :] = [(i-1)*3 + 1, (i-1)*3 + 2,(i-1)*3 + 3]
    
end

EVpl
# Epl = EVpl


894-element Array{Any,1}:
 [1,2]      
 [2,4]      
 [1,4]      
 [5,6]      
 [6,8]      
 [5,8]      
 [9,10]     
 [10,12]    
 [9,12]     
 [13,14]    
 [14,16]    
 [13,16]    
 [17,18]    
 ⋮          
 [1177,1178]
 [1178,1180]
 [1177,1180]
 [1181,1182]
 [1182,1184]
 [1181,1184]
 [1185,1186]
 [1186,1188]
 [1185,1188]
 [1189,1190]
 [1190,1192]
 [1189,1192]

## FElar

In [47]:
# nzind2sparse(nzind)

FElar = spzeros(nfaces, (3*(nfaces)))
for i = 1:nfaces
    FElar[i, (i-1)*3 + 1] = 1
    FElar[i, (i-1)*3 + 2] = 1
    FElar[i, (i-1)*3 + 3] = 1
end


In [38]:
FEpl

299×3 Array{Int64,2}:
        1         2         3
        4         5         6
        7         8         9
       10        11        12
       13        14        15
       16        17        18
       19        20        21
       22        23        24
       25        26        27
       28        29        30
       31        32        33
       34        35        36
       37        38        39
        ⋮                    
      862       863       864
      865       866       867
      868       869       870
      871       872       873
      874       875       876
      877       878       879
      880       881       882
      883       884       885
      886       887       888
      889       890       891
      892       893       894
 74448900  77554720  77556720

In [11]:
# EVpl = collect(Eset)

894-element Array{Any,1}:
 [1,2]      
 [2,4]      
 [1,4]      
 [5,6]      
 [6,8]      
 [5,8]      
 [9,10]     
 [10,12]    
 [9,12]     
 [13,14]    
 [14,16]    
 [13,16]    
 [17,18]    
 ⋮          
 [1177,1178]
 [1178,1180]
 [1177,1180]
 [1181,1182]
 [1182,1184]
 [1181,1184]
 [1185,1186]
 [1186,1188]
 [1185,1188]
 [1189,1190]
 [1190,1192]
 [1189,1192]

In [12]:
function arrayofarray2arrayd2d(d)
    data = Array(Float64,length(d),length(d[1]))
    for i in 1:length(d)
        for j in 1:length(d[1])
            data[i,j] = d[i][j]
        end
    end
    return data
end

arrayofarray2arrayd2d (generic function with 1 method)

## Clean vertexes

In [14]:
oo = collect(zip([1,2,3],[4,5,6]))

3-element Array{Tuple{Int64,Int64},1}:
 (1,4)
 (2,5)
 (3,6)

In [16]:
collect(zip([10,2,3], range(1,3)))

3-element Array{Tuple{Int64,Int64},1}:
 (10,1)
 (2,2) 
 (3,3) 

In [17]:
sort(collect(zip([10,2,3], range(1,3))))

3-element Array{Tuple{Int64,Int64},1}:
 (2,2) 
 (3,3) 
 (10,1)

In [19]:

function conv2array_of_float_arrays(array2d)

    test_vertex_float = float(array2d)

    list_of_vertexes = Array[]
    for i in 1:size(test_vertex_float, 1)
        push!(list_of_vertexes, test_vertex_float[i,:])
    end
    return list_of_vertexes
end
    

conv2array_of_float_arrays (generic function with 1 method)

In [20]:
function remove_double_vertexes_alternative(V)
    """ Return reduced vertex list wiht search table.
    
    Alternativte removing of doublefaces. Hopefully more memory efficient
    """
    X = range(1, size(V,1))
    # Vs = [v for (v, x) in VIsorted]
    # Is = [x for (v, x) in VIsorted]
    Vs = []
#     Is = [0]*size(V, 1)
#     Is = zeros( Int64, size(test_vertex, 1))
    
    Is = Dict()

    prevv = nothing
    i = 1
    sorted_vertex_id_x = sortperm(collect(zip(test_vertex[:,1], test_vertex[:,2])))
               sortperm(collect(zip(test_vertex[:,1], test_vertex[:,2])))
#     for couple in sort(collect(zip(X, conv2array_of_float_arrays(V))))
    for x in sorted_vertex_id_x
        v = V[x,:]
#         x = 
#         x, v = couple
        println(v, prevv, v.==prevv)
        if v == prevv
            # prev index was increased
            Is[x] = i - 1
        else
            push!(Vs, v)
            Is[x] = i
            i = i + 1
            prevv = v
        end
    end
    
    vertex_reduced_list = Vs
    vertex_search_table = Is
    return vertex_reduced_list, vertex_search_table
end

remove_double_vertexes_alternative (generic function with 1 method)

In [21]:

sortperm(collect(zip(test_vertex[:,1], test_vertex[:,2])))

LoadError: UndefVarError: test_vertex not defined

In [22]:
vtfl = conv2array_of_float_arrays(test_vertex)
vtfl

LoadError: UndefVarError: test_vertex not defined

In [23]:
[1 2 3 4] == [1 2 3 4]

true

In [24]:
dctd = Dict()
dctd["aho"] = 5
dctd["ahoi"] = 7

print(dctd)


Dict{Any,Any}(Pair{Any,Any}("aho",5),Pair{Any,Any}("ahoi",7))

In [25]:
sortperm([(6, 2), (2, 6), (1, 3)])

3-element Array{Int64,1}:
 3
 2
 1

In [26]:
a = sortrowsperm([ 1 2; 3 4; 1 1 ])


LoadError: UndefVarError: sortrowsperm not defined

## Construct EVlar


In [54]:
nedges = size(EVpl, 1)

894

In [56]:

EVlar = spzeros(Int8, nedges + 1 , nvertices + 1)

for i = 1:nedges
    EVlar[i, EVpl[i][1]] = 1
    EVlar[i, EVpl[i][2]] = -1
end

EVlar


895×1193 sparse matrix with 1788 Int8 nonzero entries:
	[1   ,    1]  =  1
	[3   ,    1]  =  1
	[1   ,    2]  =  -1
	[2   ,    2]  =  1
	[2   ,    4]  =  -1
	[3   ,    4]  =  -1
	[4   ,    5]  =  1
	[6   ,    5]  =  1
	[4   ,    6]  =  -1
	[5   ,    6]  =  1
	⋮
	[891 , 1185]  =  1
	[889 , 1186]  =  -1
	[890 , 1186]  =  1
	[890 , 1188]  =  -1
	[891 , 1188]  =  -1
	[892 , 1189]  =  1
	[894 , 1189]  =  1
	[892 , 1190]  =  -1
	[893 , 1190]  =  1
	[893 , 1192]  =  -1
	[894 , 1192]  =  -1

In [29]:
u = [1 1; 2 2]

2×2 Array{Int64,2}:
 1  1
 2  2

# FE

In [30]:
faces[1][2]

LoadError: BoundsError

In [31]:

FE = spzeros(Int8, nfaces + 1 , nvertices +1 )
for i = 1:nfaces
    FE[i, faces[i][1]] = 1
    FE[i, faces[i][2]] = 1
    FE[i, faces[i][3]] = 1
end

LoadError: BoundsError

In [32]:

include("../src/plasm.jl")

visualize_boundary (generic function with 1 method)

In [57]:

visualize_numbers([V, EVlar, FElar], 2)

1


LoadError: BoundsError: attempt to access 0-element Array{Int64,1} at index [1]

# Test visualization using LAR and Plasm

In [34]:
V = [
    1 1
    2 1
    1 2
    2 2
    ]
EV = sparse([
    1 -1 0 0
    0 1 -1 0
    -1 0 1 0
])
FE = sparse([
        1 1 -1
        -1 -1 1
])

2×3 sparse matrix with 6 Int64 nonzero entries:
	[1, 1]  =  1
	[2, 1]  =  -1
	[1, 2]  =  1
	[2, 2]  =  -1
	[1, 3]  =  -1
	[2, 3]  =  1

In [35]:
#visualize_numbers([V, EV, FE], 2)

# Unittest

In [36]:
# test
test_vertex = [ 1 2; 2 3; 4 1; 2 3]
Vs, Is = remove_double_vertexes_alternative(test_vertex)

for i in 1:size(test_vertex, 1)
    v1 = Vs[Is[i]] 
    v2 = test_vertex[i,:]
    assert(v1 == v2)
end

[1,2]nothingBool[false,false]
[2,3][1,2]Bool[false,false]
[2,3][2,3]Bool[true,true]
[4,1][2,3]Bool[false,false]
