Goal of this script is to obtain 
vertex, edge, face 


V, EV

In [1]:
pwd()


"/home/mjirik/projects/lario3d.jl/notebooks"

# Read obj file

In [2]:

f = open("../test/smallbb2.obj");
lines = readlines(f)

nvertices = 0
nfaces = 0
for line in lines
    if line[1] == 'v'
        nvertices = nvertices + 1
    elseif line[1] == 'f'
        nfaces = nfaces + 1
    end
end
    


In [3]:
A = rand(4,3);

B = view(A, 1:3, 1:2);

for i in eachindex(B)
   @show i
end


i = CartesianIndex{2}((1,1))
i = CartesianIndex{2}((2,1))
i = CartesianIndex{2}((3,1))
i = CartesianIndex{2}((1,2))
i = CartesianIndex{2}((2,2))
i = CartesianIndex{2}((3,2))


In [4]:
B[1,2]

0.6509027158104062

In [5]:

vertices = Array(Float64, nvertices + 1, 3)
faces = Array(Int64, nfaces + 1 , 3)
print(size(vertices))
ivertices = 1
ifaces = 1

for line in lines
    lsplit = split(line)
    if line[1] == 'v'
        for i=2:4
            vertices[ivertices, i - 1] = parse(Float64, lsplit[i])
        end
        ivertices = nvertices + 1
    elseif line[1] == 'f'
        for i=2:4
            faces[ifaces, i - 1] = parse(Int64, lsplit[i])
        end
        ifaces = ifaces + 1
    end
end


(1193,3)

# Check Julia

In [6]:
dcta = Dict("a" => 1, "b" => 2, "c" => 3)
dcta["f"] = 13
dcta

Dict{String,Int64} with 4 entries:
  "f" => 13
  "c" => 3
  "b" => 2
  "a" => 1

In [7]:
(1 , 5)


A = [(1,5), (15,18), (17,16,"asd"), (18,1,1)]

4-element Array{Tuple{Int64,Int64,Vararg{Any,N}},1}:
 (1,5)        
 (15,18)      
 (17,16,"asd")
 (18,1,1)     

In [8]:
i = 3
sort([faces[i, 1],  faces[i, 2]])

2-element Array{Int64,1}:
  9
 10

## Edges

In [9]:
Eset = Set()

for i = 1:nfaces
    
    push!(Eset, sort([faces[i, 1], faces[i, 2]]))
    push!(Eset, sort([faces[i, 2], faces[i, 3]]))
    push!(Eset, sort([faces[i, 3], faces[i, 1]]))
    
end

Eset


Set(Any[[1158,1160],[394,396],[97,98],[329,332],[1050,1052],[922,924],[553,556],[1,4],[341,342],[349,350]  …  [830,832],[1041,1044],[153,154],[21,24],[361,362],[577,580],[305,308],[1005,1008],[61,64],[478,480]])

In [10]:
E = collect(Eset)

894-element Array{Any,1}:
 [1158,1160]
 [394,396]  
 [97,98]    
 [329,332]  
 [1050,1052]
 [922,924]  
 [553,556]  
 [1,4]      
 [341,342]  
 [349,350]  
 [509,510]  
 [334,336]  
 [977,980]  
 ⋮          
 [369,370]  
 [870,872]  
 [830,832]  
 [1041,1044]
 [153,154]  
 [21,24]    
 [361,362]  
 [577,580]  
 [305,308]  
 [1005,1008]
 [61,64]    
 [478,480]  

## Construct EV

In [11]:
nedges = size(E, 1)

894

In [12]:
FV = spzeros(Int8, nfaces, nvertices)

EV = spzeros(Int8, nedges + 1 , nvertices + 1)

for i = 1:nedges
    EV[i, E[i][1]] = 1
    EV[i, E[i][2]] = 1
end

EV


895×1193 sparse matrix with 1788 Int8 nonzero entries:
	[8   ,    1]  =  1
	[144 ,    1]  =  1
	[144 ,    2]  =  1
	[163 ,    2]  =  1
	[8   ,    4]  =  1
	[163 ,    4]  =  1
	[383 ,    5]  =  1
	[857 ,    5]  =  1
	[452 ,    6]  =  1
	[857 ,    6]  =  1
	⋮
	[860 , 1185]  =  1
	[37  , 1186]  =  1
	[677 , 1186]  =  1
	[677 , 1188]  =  1
	[860 , 1188]  =  1
	[429 , 1189]  =  1
	[532 , 1189]  =  1
	[532 , 1190]  =  1
	[726 , 1190]  =  1
	[429 , 1192]  =  1
	[726 , 1192]  =  1

# Visualization using LAR and Plasm

In [13]:
V = [
    0 0 0
    1 0 0
    0 1 0
    0 0 1
    ]

4×3 Array{Int64,2}:
 0  0  0
 1  0  0
 0  1  0
 0  0  1

In [14]:
EV = [
    1 -1 0 0
    0 1 -1 0
    -1 0 1 0
]

3×4 Array{Int64,2}:
  1  -1   0  0
  0   1  -1  0
 -1   0   1  0

In [15]:
FE = [
    1
    1 
    1
]

3-element Array{Int64,1}:
 1
 1
 1

In [16]:
include("../src/plasm.jl")

LoadError: type Array has no field nzind

In [17]:
set("asdf","sdf")

LoadError: UndefVarError: set not defined