In [1]:

include("../src/plasm.jl")
include("../src/read.jl")
include("../src/surface.jl")
include("../src/representation.jl")
include("../src/import3d.jl")


thresholding (generic function with 1 method)

In [2]:
## Artifical data
data3d = zeros(Int16,5,4,3)
data3d[2:4,2:3,2] = 10
# data3d

voxelsize_mm = [0.5, 0.9, 0.8]
threshold=0

0

## Get vertices and count the voxels (* 4 = face number)

In [3]:
verts, nvoxels = vertices_and_count_voxels_as_the_square_face_preprocessing(data3d, voxelsize_mm)
# get_index(sz, 0, 0, 1)

(
[0.0 0.0 0.0; 0.5 0.0 0.0; … ; 2.0 3.6 2.4; 2.5 3.6 2.4],

6)

In [4]:
verts

120×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.5  0.0  0.0
 1.0  0.0  0.0
 1.5  0.0  0.0
 2.0  0.0  0.0
 2.5  0.0  0.0
 0.0  0.9  0.0
 0.5  0.9  0.0
 1.0  0.9  0.0
 1.5  0.9  0.0
 2.0  0.9  0.0
 2.5  0.9  0.0
 0.0  1.8  0.0
 ⋮            
 0.0  2.7  2.4
 0.5  2.7  2.4
 1.0  2.7  2.4
 1.5  2.7  2.4
 2.0  2.7  2.4
 2.5  2.7  2.4
 0.0  3.6  2.4
 0.5  3.6  2.4
 1.0  3.6  2.4
 1.5  3.6  2.4
 2.0  3.6  2.4
 2.5  3.6  2.4

## Create square face

In [5]:
faces = create_square_faces(data3d, nvoxels, threshold)
# get_index(sz, 0,0,0)
faces

36×4 Array{Int64,2}:
 75  45  39  69
 44  38  39  45
 74  44  45  75
 69  39  38  68
 75  69  68  74
 74  68  38  44
 76  46  40  70
 45  39  40  46
 75  45  46  76
 70  40  39  69
 76  70  69  75
 75  69  39  45
 77  47  41  71
  ⋮            
 82  52  46  76
 51  45  46  52
 81  51  52  82
 76  46  45  75
 82  76  75  81
 81  75  45  51
 83  53  47  77
 52  46  47  53
 82  52  53  83
 77  47  46  76
 83  77  76  82
 82  76  46  52

## Double face removal


In [6]:
new_verts, new_faces = keep_surface_faces(verts, faces)

(
[0.0 0.0 0.0; 0.0 0.0 0.8; … ; 2.5 3.6 1.6; 2.5 3.6 2.4],

[30 26 46 50; 50 46 66 70; … ; 31 27 26 30; 47 46 26 27])

In [7]:
new_verts

120×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.8
 0.0  0.0  1.6
 0.0  0.0  2.4
 0.0  0.9  0.0
 0.0  0.9  0.8
 0.0  0.9  1.6
 0.0  0.9  2.4
 0.0  1.8  0.0
 0.0  1.8  0.8
 0.0  1.8  1.6
 0.0  1.8  2.4
 0.0  2.7  0.0
 ⋮            
 2.5  1.8  0.0
 2.5  1.8  0.8
 2.5  1.8  1.6
 2.5  1.8  2.4
 2.5  2.7  0.0
 2.5  2.7  0.8
 2.5  2.7  1.6
 2.5  2.7  2.4
 2.5  3.6  0.0
 2.5  3.6  0.8
 2.5  3.6  1.6
 2.5  3.6  2.4

In [8]:
verts = new_verts
faces = new_faces

22×4 Array{Int64,2}:
 30  26  46  50
 50  46  66  70
 87  86  66  67
 70  66  86  90
 35  31  30  34
 75  74  94  95
 91  87  67  71
 71  67  47  51
 95  94  90  91
 54  50  70  74
 67  66  46  47
 51  47  27  31
 91  90  86  87
 55  54  74  75
 74  70  90  94
 95  91  71  75
 34  30  50  54
 55  51  31  35
 75  71  51  55
 35  34  54  55
 31  27  26  30
 47  46  26  27

## Triangulation

In [9]:
trifaces = triangulation(faces)

44×3 Array{Int64,2}:
 30  46  50
 30  26  46
 50  66  70
 50  46  66
 87  66  67
 87  86  66
 70  86  90
 70  66  86
 35  30  34
 35  31  30
 75  94  95
 75  74  94
 91  67  71
  ⋮        
 34  50  54
 34  30  50
 55  31  35
 55  51  31
 75  51  55
 75  71  51
 35  54  55
 35  34  54
 31  26  30
 31  27  26
 47  26  27
 47  46  26

## Visualization

In [10]:
check_vf(verts, trifaces)
visualize_numbers(to_lar(verts, trifaces), 0.5)

vertex index index higher than voxel number
faces min 26, faces max 95, vertex number 120
XgeModule::init_started
Creating shared GLCanvas...
shared GLCanvas created
XgeModule::init_finished
Evaluating fenvs.py..
('...fenvs.py imported in', 0.004686000000000079, 'seconds')
centre
centre
centre
Building batches from Hpc....
...done in 27 msec
Optimizing the octree....
   Number of input batches 3487
   total number vertices    912
   Number of output batches 456
   Batch vertex media       2
...done in 5 msec
Building octree from 456 batches....
Scene number of nodes of the octree 644
Scene max depth                     4
Scene number of batches             456
...done in 0 msec


![hexagon](https://raw.githubusercontent.com/mjirik/lario3d.jl/master/graphics/import3d_no_inner_faces.png)

2