Goal of this script is to obtain 
vertex, edge, face 


V, EV

In [1]:
# pwd()

include("../src/plasm.jl")
include("../src/read.jl")
include("../src/representation.jl")
include("../src/sampledata.jl")

tetrahedron (generic function with 1 method)

In [73]:
# hexaogon
# 
#    3 -- 4
#  /  \ /  \
# 1 -- 2 -- 5
#  \  / \  /
#   7 -- 8
hexagon_vertices, hexagon_faces = hexagon()
hexagon_vertices = [0. 0.; 2. 0.; 1. 2.; 3. 2; 4. 0.; 3. -2.; 1. -2]
hexagon_faces = [ 1 2 3; 2 4 3; 4 2 5; 5 2 6; 2 7 6; 2 1 7]
# maximum(test_faces0)



6×3 Array{Int64,2}:
 1  2  3
 2  4  3
 4  2  5
 5  2  6
 2  7  6
 2  1  7

# Read obj file

# Check Julia

## Vertices

In [3]:
V = vertices

LoadError: UndefVarError: vertices not defined

## EV naive

In [4]:
function get_EVinds_naive(faces, nfaces=nothing)
    if nfaces == nothing
        nfaces = size(faces,1)
    end
    # Eset = Set()
    Einds = []
    EVinds = []
    FEinds = Array(Int64, nfaces, 3)

    for i = 1:nfaces

        push!(EVinds, sort([faces[i, 1], faces[i, 2]]))
        push!(EVinds, sort([faces[i, 2], faces[i, 3]]))
        push!(EVinds, sort([faces[i, 3], faces[i, 1]]))

        FEinds[i, :] = [(i-1)*3 + 1, (i-1)*3 + 2,(i-1)*3 + 3]

    end

    return EVinds
end
# Epl = EVpl


get_EVinds_naive (generic function with 2 methods)

In [5]:
# tohle bude patrně blbost
# nzind2sparse(nzind)
function get_FElar_naive(nfaces)

    FElar = spzeros(Int8, nfaces, (3*(nfaces)))
    for i = 1:nfaces
        FElar[i, (i-1)*3 + 1] = 1
        FElar[i, (i-1)*3 + 2] = 1
        FElar[i, (i-1)*3 + 3] = 1
    end
    return FElar
end


get_FElar_naive (generic function with 1 method)

# EV no double edges

In [74]:
faces = hexagon_faces
nfaces = size(hexagon_faces, 1)

6

In [75]:

    
#test
assert(1 == face_orientation([1 2 3]))
assert(-1 == face_orientation([1 3 2]))

In [8]:
# get_FEinds_and_EVinv(hexagon_faces, size(hexagon_faces, 1))

In [76]:

# test
FEinds, EVinds = get_FEinds_and_EVinds(hexagon_faces)
assert(size(FEinds,1) == 6)
assert(size(FEinds,2) == 3)
assert(size(EVinds,1) == 12)
assert(size(EVinds,2) == 2)
# full(EVinds)


# TODO FElar EVlar

In [77]:
nedges = size(EVinds, 1)
nfaces = size(hexagon_faces, 1)
nvertices = size(hexagon_vertices, 1)

7

In [78]:
FElar = convert_to_FElar(hexagon_faces, FEinds, nfaces, nedges)
full(FElar)

6×12 Array{Int8,2}:
  1   1  -1   0   0   0   0   0   0   0   0  0
  0  -1   0  -1   1   0   0   0   0   0   0  0
  0   0   0   0  -1  -1   1   0   0   0   0  0
  0   0   0   0   0   0  -1  -1   1   0   0  0
  0   0   0   0   0   0   0   0  -1  -1   1  0
 -1   0   0   0   0   0   0   0   0   0  -1  1

In [79]:

EVlar = convert_to_EVlar(EVinds, nedges, nvertices)
full(EVlar)

12×7 Array{Int8,2}:
 -1   1   0   0   0   0  0
  0  -1   1   0   0   0  0
 -1   0   1   0   0   0  0
  0   0  -1   1   0   0  0
  0  -1   0   1   0   0  0
  0   0   0  -1   1   0  0
  0  -1   0   0   1   0  0
  0   0   0   0  -1   1  0
  0  -1   0   0   0   1  0
  0   0   0   0   0  -1  1
  0  -1   0   0   0   0  1
 -1   0   0   0   0   0  1

In [13]:
# Visualization 

In [68]:
check_vf(hexagon_vertices, hexagon_faces, true)

faces min 1, faces max 7, vertex number 7


In [15]:

visualize_numbers([hexagon_vertices, EVlar, FElar], 2)

XgeModule::init_started
Creating shared GLCanvas...
shared GLCanvas created
XgeModule::init_finished
Evaluating fenvs.py..
('...fenvs.py imported in', 0.007283999999999957, 'seconds')
centre
centre
centre
Building batches from Hpc....
...done in 1 msec
Optimizing the octree....
   Number of input batches 235
   total number vertices    130
   Number of output batches 65
   Batch vertex media       2
...done in 0 msec
Building octree from 65 batches....
Scene number of nodes of the octree 130
Scene max depth                     4
Scene number of batches             65
...done in 0 msec


![hexagon](https://raw.githubusercontent.com/mjirik/LarSurf.jl/master/graphics/hexagon_LarSurfjl.png)

In [16]:
e, ev, fe = to_lar(hexagon_vertices, hexagon_faces)

visualize_numbers([e, ev, fe], 2)

XgeModule::init_started
Creating shared GLCanvas...
shared GLCanvas created
XgeModule::init_finished
Evaluating fenvs.py..
('...fenvs.py imported in', 0.0049919999999999964, 'seconds')
centre
centre
centre
Building batches from Hpc....
...done in 2 msec
Optimizing the octree....
   Number of input batches 235
   total number vertices    130
   Number of output batches 65
   Batch vertex media       2
...done in 0 msec
Building octree from 65 batches....
Scene number of nodes of the octree 130
Scene max depth                     4
Scene number of batches             65
...done in 0 msec


In [17]:
-


# vn = size(vertices, 1)
# if mn < 1
#     println("vertex index lower than 1")
#     println("faces min $(mn), faces max $(mx), vertex number $(vn)")
# end

- (generic function with 190 methods)

In [18]:
full(fe)

6×12 Array{Int8,2}:
  1   1  -1   0   0   0   0   0   0   0   0  0
  0  -1   0  -1   1   0   0   0   0   0   0  0
  0   0   0   0  -1  -1   1   0   0   0   0  0
  0   0   0   0   0   0  -1  -1   1   0   0  0
  0   0   0   0   0   0   0   0  -1  -1   1  0
 -1   0   0   0   0   0   0   0   0   0  -1  1

In [19]:

filename = "../test/smallbb2.obj"
vertices, faces = read_obj(filename)
nvertices = size(vertices,1)
nfaces = size(faces,1)

# assert(nvertices == 1192)
# assert(nfaces == 298)
# println(nfaces , " " , nvertices)

298

In [20]:
EVlar, FElar = to_lar(vertices, faces)

check_vf(vertices, faces, true)
check_vevfe(vertices, EVlar, FElar)
visualize_numbers([vertices, EVlar, FElar], 2)

faces min 1, faces max 1192, vertex number 1192
Different number of vertices in EV and V
Minimum value of EV should be -1 and it is -1
Maximum value of EV should be 1 and it is 1
Element type of EV should be Int8 and it is Float64


LoadError: type Array has no field nzind

In [21]:
full(x)

LoadError: UndefVarError: x not defined

In [22]:
dctd = Dict()
dctd["aho"] = [5, 7]
dctd["ahoi"] = [3, 12]

dctd[tuple(11, 15)] = 5
dctd[tuple([12, 17]...)] = "yop"

println(dctd)
haskey(dctd, "aho")
println(haskey(dctd, (11, 15)))



dctd[(12,17)]


Dict{Any,Any}(Pair{Any,Any}("aho",[5,7]),Pair{Any,Any}((11,15),5),Pair{Any,Any}((12,17),"yop"),Pair{Any,Any}("ahoi",[3,12]))
true


"yop"

In [23]:
#blbost
EVinds = get_EVinds_naive(hexagon_faces)
FElar = get_FElar_naive(size(hexagon_faces, 1))

6×18 sparse matrix with 18 Int8 nonzero entries:
	[1 ,  1]  =  1
	[1 ,  2]  =  1
	[1 ,  3]  =  1
	[2 ,  4]  =  1
	[2 ,  5]  =  1
	[2 ,  6]  =  1
	[3 ,  7]  =  1
	[3 ,  8]  =  1
	[3 ,  9]  =  1
	[4 , 10]  =  1
	[4 , 11]  =  1
	[4 , 12]  =  1
	[5 , 13]  =  1
	[5 , 14]  =  1
	[5 , 15]  =  1
	[6 , 16]  =  1
	[6 , 17]  =  1
	[6 , 18]  =  1

## FElar

In [24]:
# face orientation
test_face1 = [1, 3, 5]
test_face2 = [3, 5, 1]



3-element Array{Int64,1}:
 3
 5
 1

In [25]:
# FE = get_FElar_naive(nfaces)
FEpl

LoadError: UndefVarError: FEpl not defined

In [26]:
# EVpl = collect(Eset)

In [27]:
function arrayofarray2arrayd2d(d)
    data = Array(Float64,length(d),length(d[1]))
    for i in 1:length(d)
        for j in 1:length(d[1])
            data[i,j] = d[i][j]
        end
    end
    return data
end

arrayofarray2arrayd2d (generic function with 1 method)

## Clean vertexes

In [28]:
oo = collect(zip([1,2,3],[4,5,6]))

3-element Array{Tuple{Int64,Int64},1}:
 (1,4)
 (2,5)
 (3,6)

In [29]:
collect(zip([10,2,3], range(1,3)))

3-element Array{Tuple{Int64,Int64},1}:
 (10,1)
 (2,2) 
 (3,3) 

In [30]:
sort(collect(zip([10,2,3], range(1,3))))

3-element Array{Tuple{Int64,Int64},1}:
 (2,2) 
 (3,3) 
 (10,1)

In [31]:

function conv2array_of_float_arrays(array2d)

    test_vertex_float = float(array2d)

    list_of_vertexes = Array[]
    for i in 1:size(test_vertex_float, 1)
        push!(list_of_vertexes, test_vertex_float[i,:])
    end
    return list_of_vertexes
end
    

conv2array_of_float_arrays (generic function with 1 method)

In [32]:
function remove_double_vertexes_alternative(V)
    """ Return reduced vertex list wiht search table.
    
    Alternativte removing of doublefaces. Hopefully more memory efficient
    """
    X = range(1, size(V,1))
    # Vs = [v for (v, x) in VIsorted]
    # Is = [x for (v, x) in VIsorted]
    Vs = []
#     Is = [0]*size(V, 1)
#     Is = zeros( Int64, size(test_vertex, 1))
    
    Is = Dict()

    prevv = nothing
    i = 1
    sorted_vertex_id_x = sortperm(collect(zip(test_vertex[:,1], test_vertex[:,2])))
               sortperm(collect(zip(test_vertex[:,1], test_vertex[:,2])))
#     for couple in sort(collect(zip(X, conv2array_of_float_arrays(V))))
    for x in sorted_vertex_id_x
        v = V[x,:]
#         x = 
#         x, v = couple
        println(v, prevv, v.==prevv)
        if v == prevv
            # prev index was increased
            Is[x] = i - 1
        else
            push!(Vs, v)
            Is[x] = i
            i = i + 1
            prevv = v
        end
    end
    
    vertex_reduced_list = Vs
    vertex_search_table = Is
    return vertex_reduced_list, vertex_search_table
end

remove_double_vertexes_alternative (generic function with 1 method)

In [33]:

# sortperm(collect(zip(test_vertex[:,1], test_vertex[:,2])))

In [34]:
vtfl = conv2array_of_float_arrays(test_vertex)
vtfl

LoadError: UndefVarError: test_vertex not defined

In [35]:
[1 2 3 4] == [1 2 3 4]

true

In [36]:
sortperm([(6, 2), (2, 6), (1, 3)])

3-element Array{Int64,1}:
 3
 2
 1

## Construct EVlar


In [37]:
nedges = size(EVpl, 1)

LoadError: UndefVarError: EVpl not defined

In [38]:

EVlar = spzeros(Int8, nedges , nvertices )

for i = 1:nedges
    EVlar[i, EVpl[i][1]] = -1
    EVlar[i, EVpl[i][2]] = 1
end

EVlar


LoadError: UndefVarError: EVpl not defined

# FE

In [39]:
faces[1,2]

2

In [40]:
function get_FElar_naive(faces, nvertices=nothing, nfaces=nothing)
    if nfaces == nothing
        nfaces = size(faces,1)
    end
    if nvertices == nothing
        nvertices = maximum(faces)
    end
    # not oriented verison of faces
    FE = spzeros(Int8, nfaces, nvertices)
    for i = 1:nfaces
        FE[i, faces[i, 1]] = 1
        FE[i, faces[i, 2]] = 1
        FE[i, faces[i, 3]] = -1
    end
    
    return FE
end

get_FElar_naive (generic function with 3 methods)

In [41]:

function get_FElar(faces, nvertices=nothing, nfaces=nothing)
    if nfaces == nothing
        nfaces = size(faces,1)
    end
    if nvertices == nothing
        nvertices = maximum(faces)
    end
    FE = spzeros(Int8, nfaces, nvertices)
    for i = 1:nfaces
        sgn = face_orientation(faces[i, :])
        ordered_face = sort(faces[i, :])
        FE[i, ordered_face[1]] = sgn * 1
        FE[i, ordered_face[2]] = sgn * 1
        FE[i, ordered_face[3]] = sgn * -1
    end
    return FE
end


#test

get_FElar (generic function with 3 methods)

In [42]:

test_FElar = get_FElar(hexagon_faces)
# test_FElar[2 , 4]
full(test_FElar)
# test_FElar.nzval

6×7 Array{Int8,2}:
  1   1  -1   0   0   0  0
  0  -1  -1   1   0   0  0
  0  -1   0  -1   1   0  0
  0  -1   0   0  -1   1  0
  0  -1   0   0   0  -1  1
 -1  -1   0   0   0   0  1

In [43]:
vertices[7,:]
minimum(vertices)

0.0

In [44]:

visualize_numbers([vertices, EVlar, FElar], 2)

LoadError: BoundsError: attempt to access 0-element Array{Int64,1} at index [1]

# Debug version of visualize_numbers

In [45]:
function lar2plasm(EV, FE)
    EV = sparse(EV)
    faces = Array{Array{Int64, 1}, 1}()

    for f in 1:size(FE, 1)

        verts = Array{Int64, 1}()
        done = Array{Int64, 1}()
        face = FE[f, :]
        edges = EV[face.nzind, :]

        push!(done, 1)
        vs = edges[1, :].nzind
        if face.nzval[1] < 0
            vs = vs[end:-1:1]
        end
        startv, nextv = vs

        println("startv ", startv)
        push!(verts, startv)
        while nextv != startv
            println("ve while", edges[:, nextv].nzind, done, nextv, edges)
            ednz = edges[:, nextv].nzind
            println("wh 1")
            eall = setdiff(ednz, done)
            println("wh 2", eall)
            e = eall[1]
            println("wh 3")
            push!(done, e)
            vs = edges[e, :].nzind
            if face.nzval[e] < 0
                vs = vs[end:-1:1]
            end
            curv, nextv = vs
            push!(verts, curv)
            println("wh 5 ", nextv)
        end

        push!(faces, verts)
    end

    "FV = " * string(faces)[15:end]
end

function lar2py(V, EV)
    text = "V = [[0,0]"
    for i in 1:size(V, 1)
        text = text * "," * string(vec(V[i, :]))
    end
    text = text * "]\n"
    
    text = text * "EV = ["
    for i in 1:size(EV, 1)
        if i > 1 text = text * "," end
        text = text * string(EV[i, :].nzind)
    end
    text = text * "]"
    return text
end


function visualize_numbers(set, font_size)
    """
    seg = [V, EV, FE]
    """

    f = open("tmp.py", "w")

    file_content = "from larlib import *\n" *
        lar2py(set[1], set[2]) * "\n" *
        lar2plasm(set[2], set[3]) * "\n" *
        "VV = AA(LIST)(range(len(V)))\n" *
        "submodel = STRUCT(MKPOLS((V,EV)))\n" *
        "VIEW(larModelNumbering(1,1,1)(V,[VV,EV,FV],submodel,$font_size))\n"
    print(file_content)
    write(f, file_content)

    close(f)
#     run(`python tmp.py`)
end

function visualize_boundary(set, boundary, font_size)
    f = open("tmp.py", "w")
    file_content =  "from larlib import *\n" *
        lar2py(set[1], set[2]) * "\n" *
        lar2plasm(set[2], set[3]) * "\n" *
        "VV = AA(LIST)(range(len(V)))\n" *
        "submodel = STRUCT(MKPOLS((V,EV)))\n" *
        "model = larModelNumbering(1,1,1)(V,[VV,EV,FV],submodel,$font_size)\n" *
        lar2py(set[1], set[2][boundary.nzind, :]) * "\n" *
        "overmodel = STRUCT(MKPOLS((V,EV)))\n" *
        "VIEW(STRUCT([model, COLOR(RED)(overmodel)]))"
    print(file_content)
    write(f, file_content)

    close(f)
    run(`python tmp.py`)
end

visualize_boundary (generic function with 1 method)

In [46]:
test_V = [
    1 1
    2 1
    1 2
    2 2
    ]
test_EV = sparse([
    -1 1 0 0
    0 -1 1 0
    -1 0 1 0
])
test_FE = sparse([
        1 1 -1
        -1 -1 1
])
visualize_numbers([test_V, test_EV, test_FE], 2)

startv 1
ve while[1,2][1]2
	[1, 1]  =  -1
	[3, 1]  =  -1
	[1, 2]  =  1
	[2, 2]  =  -1
	[2, 3]  =  1
	[3, 3]  =  1
wh 1
wh 2[2]
wh 3
wh 5 3
ve while[2,3][1,2]3
	[1, 1]  =  -1
	[3, 1]  =  -1
	[1, 2]  =  1
	[2, 2]  =  -1
	[2, 3]  =  1
	[3, 3]  =  1
wh 1
wh 2[3]
wh 3
wh 5 1
startv 2
ve while[1,3][1]1
	[1, 1]  =  -1
	[3, 1]  =  -1
	[1, 2]  =  1
	[2, 2]  =  -1
	[2, 3]  =  1
	[3, 3]  =  1
wh 1
wh 2[3]
wh 3
wh 5 3
ve while[2,3][1,3]3
	[1, 1]  =  -1
	[3, 1]  =  -1
	[1, 2]  =  1
	[2, 2]  =  -1
	[2, 3]  =  1
	[3, 3]  =  1
wh 1
wh 2[2]
wh 3
wh 5 2
from larlib import *
V = [[0,0],[1,1],[2,1],[1,2],[2,2]]
EV = [[1,2],[2,3],[1,3]]
FV = [[1,2,3],[2,1,3]]
VV = AA(LIST)(range(len(V)))
submodel = STRUCT(MKPOLS((V,EV)))
VIEW(larModelNumbering(1,1,1)(V,[VV,EV,FV],submodel,2))


In [47]:
function printarr(arr)
    print(size(arr), typeof(arr), " sparse: ", issparse(arr),", min: ",  minimum(arr), ", max: ",  maximum(arr))
end

printarr (generic function with 1 method)

In [48]:
nvertices

1192

In [49]:
nfaces

298

In [50]:
printarr(vertices)

(1192,3)Array{Float64,2} sparse: false, min: 0.0, max: 6.0

In [51]:
printarr(EVlar)
# EVlar.nzind

(12,1192)SparseMatrixCSC{Int8,Int64} sparse: true, min: 0, max: 0

In [52]:
printarr(FElar)

(6,18)SparseMatrixCSC{Int8,Int64} sparse: true, min: 0, max: 1

In [53]:
vertices

1192×3 Array{Float64,2}:
 1.0  2.0  1.0
 2.0  2.0  1.0
 1.0  3.0  1.0
 2.0  3.0  1.0
 1.0  2.0  1.0
 2.0  2.0  1.0
 1.0  2.0  2.0
 2.0  2.0  2.0
 1.0  2.0  1.0
 1.0  3.0  1.0
 1.0  2.0  2.0
 1.0  3.0  2.0
 2.0  2.0  1.0
 ⋮            
 4.0  6.0  5.0
 5.0  6.0  5.0
 4.0  6.0  6.0
 5.0  6.0  6.0
 4.0  4.0  6.0
 5.0  4.0  6.0
 4.0  5.0  6.0
 5.0  5.0  6.0
 4.0  5.0  6.0
 5.0  5.0  6.0
 4.0  6.0  6.0
 5.0  6.0  6.0

In [54]:
full(EVlar)

12×1192 Array{Int8,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0

In [55]:
FElarint = sparse(Int8, FElar)
# full(FElarint)

LoadError: MethodError: no method matching sparse(::Type{Int8}, ::SparseMatrixCSC{Int8,Int64})
Closest candidates are:
  sparse(::Any, ::Any, ::Number) at sparse/sparsematrix.jl:587
  sparse(::Any, ::Any, ::AbstractArray{Bool,1}, ::Any, ::Any) at sparse/sparsematrix.jl:595
  sparse(::Any, ::Any, ::AbstractArray{T,1}) at sparse/sparsematrix.jl:589
  ...

In [56]:

visualize_numbers([vertices, EVlar, FElar], 2)

LoadError: BoundsError: attempt to access 0-element Array{Int64,1} at index [1]

In [57]:
setdiff([2,3],[1,2,3])

0-element Array{Int64,1}

In [58]:
V = [
    1 1
    2 1
    1 2
    2 2
    ]
EV = sparse([
    1 -1 0 0
    0 1 -1 0
    -1 0 1 0
])
FE = sparse([
        1 1 -1
        -1 -1 1
])
visualize_numbers([V, EV, FE], 2)

startv 1
ve while[1,2][1]2
	[1, 1]  =  1
	[3, 1]  =  -1
	[1, 2]  =  -1
	[2, 2]  =  1
	[2, 3]  =  -1
	[3, 3]  =  1
wh 1
wh 2[2]
wh 3
wh 5 3
ve while[2,3][1,2]3
	[1, 1]  =  1
	[3, 1]  =  -1
	[1, 2]  =  -1
	[2, 2]  =  1
	[2, 3]  =  -1
	[3, 3]  =  1
wh 1
wh 2[3]
wh 3
wh 5 1
startv 2
ve while[1,3][1]1
	[1, 1]  =  1
	[3, 1]  =  -1
	[1, 2]  =  -1
	[2, 2]  =  1
	[2, 3]  =  -1
	[3, 3]  =  1
wh 1
wh 2[3]
wh 3
wh 5 3
ve while[2,3][1,3]3
	[1, 1]  =  1
	[3, 1]  =  -1
	[1, 2]  =  -1
	[2, 2]  =  1
	[2, 3]  =  -1
	[3, 3]  =  1
wh 1
wh 2[2]
wh 3
wh 5 2
from larlib import *
V = [[0,0],[1,1],[2,1],[1,2],[2,2]]
EV = [[1,2],[2,3],[1,3]]
FV = [[1,2,3],[2,1,3]]
VV = AA(LIST)(range(len(V)))
submodel = STRUCT(MKPOLS((V,EV)))
VIEW(larModelNumbering(1,1,1)(V,[VV,EV,FV],submodel,2))


# Test visualization using LAR and Plasm

In [59]:
V = [
    1 1
    2 1
    1 2
    2 2
    ]
EV = sparse([
    1 -1 0 0
    0 1 -1 0
    -1 0 1 0
])
FE = sparse([
        1 1 -1
        -1 -1 1
])

2×3 sparse matrix with 6 Int64 nonzero entries:
	[1, 1]  =  1
	[2, 1]  =  -1
	[1, 2]  =  1
	[2, 2]  =  -1
	[1, 3]  =  -1
	[2, 3]  =  1

In [60]:
#visualize_numbers([V, EV, FE], 2)

In [61]:
function reindexVertexesInFaces(faces, new_indexes,
                                       index_base=0)
#     println(faces)
    for i in 1:size(faces, 1)
        for j in 1:size(faces, 2)
            faces[i, j] = new_indexes[faces[i, j] - index_base] + index_base
        end
    end
#     try
#     catch
#         println("reindexVertexInFaces exception")
#         println("fc ", face, " i ", i , " len ", size(new_indexes))
        
#     end
    return faces
    
end
    
        
#     for face in faces:
#         try:
#             for i in range(0, len(face)):
#                 face[i] = new_indexes[face[i] - index_base] + index_base
#             # face[0] = new_indexes[face[0]-1] + 1
#             # face[1] = new_indexes[face[1]-1] + 1
#             # face[2] = new_indexes[face[2]-1] + 1
#         except:
#             import traceback
#             traceback.print_exc()
#             print 'fc ', face, ' i ', i
#             print len(new_indexes)

#     return faces 
-

- (generic function with 190 methods)

In [62]:
Dict(tuple(1,2) => 1, "B" => 2)

Dict{Any,Int64} with 2 entries:
  "B"   => 2
  (1,2) => 1

In [63]:
removeDoubleVertexesAndFaces()

LoadError: UndefVarError: removeDoubleVertexesAndFaces not defined

# Unittest

In [64]:
# test
test_vertex = [ 1 2; 2 3; 4 1; 2 3; 3 3]
test_faces = [
    1 3 4;
    4 5 1;
    1 5 4
]
# test_EV = sparse([
#     1 -1 0 0
#     0 1 -1 0
#     -1 0 1 0
# ])
# test_FE = sparse([
#         1 1 -1
#         -1 -1 1
# ])
# test_faces = sparse([ 1 2; 2 3; 4 1; 2 3])

Vs, Is = remove_double_vertexes_alternative(test_vertex)

for i in 1:size(test_vertex, 1)
    v1 = Vs[Is[i]] 
    v2 = test_vertex[i,:]
    assert(v1 == v2)
end

print(Vs)

[1,2]nothingBool[false,false]
[2,3][1,2]Bool[false,false]
[2,3][2,3]Bool[true,true]
[3,3][2,3]Bool[false,true]
[4,1][3,3]Bool[false,false]
Any[[1,2],[2,3],[3,3],[4,1]]

In [65]:

reindexed_faces = reindexVertexesInFaces(copy(test_faces), Is)
println(Vs)
println(reindexed_faces)
reindexed_faces == [1 4 2; 2 3 1]


Any[[1,2],[2,3],[3,3],[4,1]]
[1 4 2; 2 3 1; 1 3 2]


false

In [66]:
fcs = removeDoubleFacesByDictAlgoritm(test_faces)

collect(fcs)

LoadError: UndefVarError: removeDoubleFacesByDictAlgoritm not defined

In [67]:

new_vertexes, new_faces = removeDoubleVertexesAndFaces(test_vertex, test_faces)

LoadError: UndefVarError: removeDoubleVertexesAndFaces not defined